name: aifw-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r py-origin/services/requirements.txt
          pip install -r py-origin/cli/requirements.txt
          python -m spacy download en_core_web_sm
          python -m spacy download xx_ent_wiki_sm
          python -m spacy download zh_core_web_sm

      - name: Start fake LLM (echo) in background
        run: |
          cd py-origin
          python -m uvicorn services.fake_llm.echo_server:app --host 127.0.0.1 --port 8801 &
          echo $! > echo_llm.pid
          for i in $(seq 1 20); do curl -sf http://127.0.0.1:8801/v1/health && break || sleep 0.5; done

      - name: Prepare OpenAI-compatible key file
        run: |
          cat > $RUNNER_TEMP/echo-apikey.json << 'JSON'
          {
            "openai-api-key": "test-local-echo",
            "openai-base-url": "http://127.0.0.1:8801/v1",
            "openai-model": "echo-001"
          }
          JSON

      - name: Run tests (direct_call / launch / call / stop)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          cd py-origin
          PROMPT="请把如下文本翻译为中文: My email address is test@example.com, and my phone number is 18744325579."
          # direct_call (in-process)
          python -m aifw direct_call --api-key-file $RUNNER_TEMP/echo-apikey.json "My email is test@example.com"

          # launch HTTP (daemonized), call, then stop
          python -m aifw launch --api-key-file $RUNNER_TEMP/echo-apikey.json --log-dest stdout || (cat ~/.aifw/aifw-server-*.log || true; exit 1)
          # wait until HTTP server is ready
          for i in $(seq 1 40); do curl -sf http://127.0.0.1:8844/api/health && break || sleep 0.5; done
          python -m aifw call --api-key-file $RUNNER_TEMP/echo-apikey.json "$PROMPT"
          python -m aifw stop || true

      - name: Teardown fake LLM
        if: always()
        run: |
          if [ -f echo_llm.pid ]; then kill $(cat echo_llm.pid) || true; fi

